#
# Copyright 2016 Freescale Semiconductor
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y += load_ddr_firmware.o
obj-$(CONFIG_DDR3_1600MTS_ONE_FW_100) += ddr3_1600mts_one_fw100/
obj-$(CONFIG_LPDDR4_3200MTS_TWO_FW_100) += lpddr4_3200mts_two_fw100/
endif
